import Header from './components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import { Mulish } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] })
const mulish = Mulish({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap'
})
import Footer from './components/Footer';
export const metadata = {
  title: 'MovieFlix',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
      <body className={inter.className} >
        <div className='parent'>
        <Header/>
        {children}
        <Footer/>
        </div>
        </body>
    </html>
  )
}
